# Generated by Django 2.1.2 on 2018-11-04 10:39

import core.models
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to=core.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_file_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.UUID('97426dc1-b930-4c0a-8fa0-fd14ca938720'), editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image_directory_path', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
