# Generated by Django 2.1.2 on 2018-11-04 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('e4e01626-8385-4ef2-b25b-a6ab7f3ffb0d'), editable=False),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b4dfbf8e-ca9f-4820-a977-2ceeadd9e8ef'), editable=False, primary_key=True, serialize=False),
        ),
    ]
